// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CardItem: typeof import('./components/card-item/index.vue')['default']
    ChartArea: typeof import('./components/chart-area/index.vue')['default']
    ChartAreaRank1: typeof import('./components/chart-area-rank1/index.vue')['default']
    ChartAreaRank2: typeof import('./components/chart-area-rank2/index.vue')['default']
    ChartBar: typeof import('./components/chart-bar/index.vue')['default']
    ChartCard: typeof import('./components/chart-card/index.vue')['default']
    ChartMbar: typeof import('./components/chart-mbar/index.vue')['default']
    Dot: typeof import('./components/dot/index.vue')['default']
    FourItemCard: typeof import('./components/four-item-card/index.vue')['default']
    HeaderItem: typeof import('./components/header-item/index.vue')['default']
    MiniProgress: typeof import('./components/mini-progress/index.vue')['default']
    ModelDimension: typeof import('./components/model-dimension/index.vue')['default']
    PageHeader: typeof import('./components/page-header/index.vue')['default']
    ProblemData: typeof import('./components/problem-data/index.vue')['default']
    ProjectAccounteChart: typeof import('./components/project-accounte-chart/index.vue')['default']
    RecordList: typeof import('./components/record-list/index.vue')['default']
    RunListCard: typeof import('./components/run-list-card/index.vue')['default']
    Table: typeof import('./components/table/index.vue')['default']
    Tabs: typeof import('./components/tabs/index.vue')['default']
    TendencyRun: typeof import('./components/tendency-run/index.vue')['default']
    Trend: typeof import('./components/trend/index.vue')['default']
    VueCountTo: typeof import('./components/vue-count-to/index.vue')['default']
  }
}

export { }
